module.exports = {
   LOGO: process.env.LOGO,
   MONGO_URI:process.env.MONGO_URI,
   SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
   SESSION_SECRET:process.env.SESSION_SECRET,
   FROM_EMAIL:process.env.FROM_EMAIL,
   FROM_EMAIL_PASSWORD: process.env.FROM_EMAIL_PASSWORD,
   AWS_ACCESS_KEY_ID:process.env.AWS_ACCESS_KEY_ID,
   AWS_SECRET_ACCESS_KEY:process.env.AWS_SECRET_ACCESS_KEY,
   S3_BUCKET_NAME:process.env.S3_BUCKET_NAME,
   STRIPE_PUBLICE_KEY:process.env.STRIPE_PUBLICE_KEY,
   STRIPE_SECRET_KEY:process.env.STRIPE_SECRET_KEY,
   PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
   PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
   BASE_URL:process.env.BASE_URL
}